name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'  # Only trigger on version tags like v1.30.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
    
      - name: Restore Dependencies
        run: dotnet restore Cameek.W3CssJs.PrismJs.csproj
    
      - name: Build Project
        run: dotnet build --configuration Release Cameek.W3CssJs.PrismJs.csproj
    
      - name: Pack NuGet Package
        run: dotnet pack --configuration Release Cameek.W3CssJs.PrismJs.csproj --output ./nuget-packages
